---
abstract: 'Manage perl installations in your $HOME'
author:
  - 'Kang-min Liu  C<< <gugod@gugod.org> >>'
build_requires:
  ExtUtils::MakeMaker: 6.59
  File::Temp: 0.2304
  IO::All: 0.51
  Path::Class: 0.33
  Test::Exception: 0.32
  Test::More: 1.001002
  Test::NoWarnings: 1.04
  Test::Output: 1.03
  Test::Simple: 1.001002
  Test::Spec: 0.47
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: mit
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: App::perlbrew
name: App-perlbrew
no_index:
  directory:
    - inc
    - t
requires:
  CPAN::Perl::Releases: 1.74
  Capture::Tiny: 0.24
  Devel::PatchPerl: 1.24
  Pod::Parser: 1.62
  Pod::Usage: 1.63
  local::lib: 2.000012
  perl: 5.8.0
resources:
  license: http://opensource.org/licenses/mit-license.php
  repository: git://github.com/gugod/App-perlbrew.git
version: 0.69
