---
abstract: 'Manage perl installations in your C<$HOME>'
author:
  - 'Kang-min Liu  C<< <gugod@gugod.org> >>'
build_requires:
  ExtUtils::MakeMaker: '6.86'
  File::Which: '1.21'
  IO::All: '0.51'
  Path::Class: '0.33'
  Pod::Markdown: '2.002'
  Test::Exception: '0.32'
  Test::More: '1.001002'
  Test::NoWarnings: '1.04'
  Test::Output: '1.03'
  Test::Simple: '1.001002'
  Test::Spec: '0.47'
  Test::TempDir::Tiny: '0.016'
configure_requires:
  Module::Build::Tiny: '0.034'
dynamic_config: 0
generated_by: 'App::ModuleBuildTiny version 0.023, CPAN::Meta::Converter version 2.150005'
license: mit
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: App-perlbrew
provides:
  App::perlbrew:
    file: lib/App/perlbrew.pm
    version: '0.83'
requires:
  CPAN::Perl::Releases: '3.24'
  Capture::Tiny: '0.36'
  Devel::PatchPerl: '1.40'
  File::Temp: '0.2304'
  JSON::PP: '0'
  Pod::Parser: '1.63'
  Pod::Usage: '1.68'
  local::lib: '2.000014'
version: '0.83'
x_serialization_backend: 'CPAN::Meta::YAML version 0.016'
