---
abstract: 'Manage perl installations in your $HOME'
author:
  - 'Kang-min Liu  C<< <gugod@gugod.org> >>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::Simple: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: mit
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: App::perlbrew
name: App-perlbrew
no_index:
  directory:
    - inc
    - t
requires:
  perl: 5.8.0
resources:
  license: http://opensource.org/licenses/mit-license.php
  repository: git://github.com/gugod/App-perlbrew.git
version: 0.17
