---
abstract: 'Manage perl installations in your $HOME'
author:
  - 'Kang-min Liu  C<< <gugod@gugod.org> >>'
build_requires:
  ExtUtils::MakeMaker: 6.59
  File::Temp: 0
  IO::All: 0
  Path::Class: 0
  Test::Exception: 0
  Test::More: 0
  Test::NoWarnings: 0
  Test::Output: 0
  Test::Simple: 0.98
  Test::Spec: 0
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: mit
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: App::perlbrew
name: App-perlbrew
no_index:
  directory:
    - inc
    - t
requires:
  CPAN::Perl::Releases: 0.76
  Capture::Tiny: 0.20
  Devel::PatchPerl: 0.76
  local::lib: 1.008004
  perl: 5.8.0
resources:
  license: http://opensource.org/licenses/mit-license.php
  repository: git://github.com/gugod/App-perlbrew.git
version: 0.59
